#!/usr/bin/env node
/**
 * placeholder.mjs — stand-in media, so the page can be built before the renders land.
 *
 *   node placeholder.mjs --spec work/scenes.json --out work/placeholder
 *                        [--stills-out src/assets/scenes]
 *
 * WHY THIS EXISTS
 *
 * The build order renders first (steps 3-7) and assembles last (step 8), and that
 * is the right default. But on the manual path the renders happen in someone
 * else's tool on someone else's schedule, and the half of the work that does NOT
 * depend on footage — engine wiring, theming, the head, the accessibility
 * contract, the tier contract — can be finished and verified meanwhile. Doing it
 * that way is how the engine's 1.13:1 button contrast on a dark ground got found
 * before a single clip existed.
 *
 * What a scaffold does NOT validate, and nobody should claim it does: seams, real
 * payload, and whether the copy is legible over real footage. Those need the real
 * thing. `budget.mjs` measuring 3.8 MB of gradients is not a payload result.
 *
 * THE SAFETY PROPERTY
 *
 * Every file written here is stamped with SCROLL_PLACEHOLDER_V1 inside its own
 * bytes. budget.mjs fails on it locally, scroll-audit.mjs fails on it at the
 * wire, and the stamp leaves when the file is replaced — there is no flag to
 * unset and nothing to remember.
 *
 * Reads the SAME spec intake.mjs consumes, so the scene list has one source.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { MARKER, stampArgs, stampPng, fileHasMarker } from './lib/provenance.mjs';

const argv = process.argv.slice(2);
const has = (n) => argv.includes('--' + n);
const flag = (n, d) => { const i = argv.indexOf('--' + n); return i === -1 ? d : argv[i + 1]; };

if (has('help') || !flag('spec', null)) {
  console.error(`usage: node placeholder.mjs --spec <scenes.json> --out <dir> [--stills-out <dir>]

Writes stamped stand-in stills and clips so the page can be assembled and audited
while the real renders are pending. Everything it writes fails the ship gates by
design; replacing a file clears its stamp automatically.`);
  process.exit(2);
}

const specPath = flag('spec', null);
const out = flag('out', null);
if (!out) { console.error('--out is required'); process.exit(2); }
if (!fs.existsSync(specPath)) { console.error(`no spec at ${specPath}`); process.exit(2); }

const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
const SCENES = spec.scenes || [];
if (!SCENES.length) { console.error('spec has no scenes'); process.exit(2); }
const ARCH = String(spec.arch || 'b').toLowerCase();
const DIVE = spec.diveDur || 8;
const CONN = spec.connDur || 5;
const BG = /^#?[0-9a-f]{6}$/i.test(String(spec.bg || '')) ? String(spec.bg).replace('#', '') : '101314';

const stillsOut = flag('stills-out', out);
fs.mkdirSync(out, { recursive: true });
fs.mkdirSync(stillsOut, { recursive: true });

if (!spawnSync('ffmpeg', ['-version']).stdout) { console.error('ffmpeg not on PATH'); process.exit(3); }

/* ffmpeg ALWAYS with -nostdin: without it ffmpeg eats the caller's stdin and any
   loop driving it gets truncated input on the next iteration. */
const ff = (args) => {
  const r = spawnSync('ffmpeg', ['-nostdin', '-y', '-loglevel', 'error', ...args], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error((r.stderr || '').trim() || 'ffmpeg failed');
};

/* Derive two companions from the brand ground so the scaffold reads as the brand
   rather than grey bars — a designer can judge type and layout against it. It is
   deliberately abstract: no watermark, because a watermark would poison every
   design screenshot the scaffold exists to produce. The embedded stamp and the
   gates are what make it safe, not how it looks. */
const shift = (hex, dr, dg, db) => {
  const n = parseInt(hex, 16);
  const c = (v, d) => Math.max(0, Math.min(255, v + d)).toString(16).padStart(2, '0');
  return c(n >> 16 & 255, dr) + c(n >> 8 & 255, dg) + c(n & 255, db);
};

const NOTE = `generated by placeholder.mjs for ${path.basename(specPath)}`;
const written = [];

function still(scene, i) {
  const file = path.join(stillsOut, `still_${scene.id}.png`);
  const lift = 10 + i * 6;
  ff(['-f', 'lavfi', '-i',
    `gradients=s=1536x1024:c0=0x${BG}:c1=0x${shift(BG, lift, lift + 4, lift + 2)}:c2=0x${shift(BG, lift + 22, lift + 6, lift + 12)}` +
    `:nb_colors=3:type=radial:x0=${420 + i * 170}:y0=${380 + i * 45}:d=1:r=25`,
    '-vf', 'vignette=angle=PI/4,noise=alls=5:allf=t+u', '-frames:v', '1', file]);
  stampPng(file, NOTE); // ffmpeg's PNG muxer ignores -metadata; stamped by hand
  written.push(file);
  return file;
}

function clipFromStill(src, dst, dur) {
  ff(['-loop', '1', '-i', src, '-t', String(dur),
    '-vf', `scale=2560:-2,zoompan=z='min(1+0.22*on/(${dur}*30),1.22)':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=1280x720:fps=30,format=yuv420p`,
    '-an', ...stampArgs(NOTE), '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '24', dst]);
  written.push(dst);
}

function connector(a, b, dst, dur) {
  ff(['-loop', '1', '-t', String(dur), '-i', a, '-loop', '1', '-t', String(dur), '-i', b,
    '-filter_complex',
    `[0:v]scale=1280:720,format=yuv420p[a];[1:v]scale=1280:720,format=yuv420p[b];` +
    `[a][b]xfade=transition=fade:duration=${Math.max(1, dur - 0.5)}:offset=0.25,fps=30[v]`,
    '-map', '[v]', '-an', ...stampArgs(NOTE), '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '24', dst]);
  written.push(dst);
}

console.log(`\nplaceholder — ${SCENES.length} scenes, architecture ${ARCH.toUpperCase()}\n`);

const stills = SCENES.map((s, i) => { const f = still(s, i); console.log(`  still     ${path.basename(f)}`); return f; });

SCENES.forEach((s, i) => {
  const name = ARCH === 'a' ? `leg_${s.id}.mp4` : `dive_${s.id}.mp4`;
  clipFromStill(stills[i], path.join(out, name), DIVE);
  console.log(`  ${ARCH === 'a' ? 'leg  ' : 'dive '}     ${name}`);
});

if (ARCH !== 'a') {
  for (let i = 0; i < SCENES.length - 1; i++) {
    const name = `conn_${i + 1}.mp4`;
    connector(stills[i], stills[i + 1], path.join(out, name), CONN);
    console.log(`  connector ${name}`);
  }
}

const unstamped = written.filter((f) => !fileHasMarker(f));
if (unstamped.length) {
  console.error(`\n✗ ${unstamped.length} file(s) did not take the stamp — do NOT rely on the gates:`);
  unstamped.forEach((f) => console.error('    ' + path.basename(f)));
  process.exit(1);
}

console.log(`\n  ${written.length} files, every one stamped ${MARKER}\n`);
console.log(`  These are UN-SHIPPABLE BY DESIGN. budget.mjs fails on them locally and`);
console.log(`  scroll-audit.mjs fails on them at the wire. Replacing a file clears its`);
console.log(`  stamp — there is no flag to unset.\n`);
console.log(`  Next: encode.sh "${out}" <public/scroll>, then build and audit the page.`);
console.log(`  The gates stay red until real renders land. That is the point.\n`);
